// Base convention plugin for every subproject.
// Provides: Kotlin JVM, Spring Boot BOM via platform(), Java 21 toolchain, JUnit 5.
plugins {
    kotlin("jvm")
}

// Access the shared version catalog (type-safe accessor generated by Gradle).
// Requires the compileOnly(files(...)) workaround in build-logic/build.gradle.kts.
val libs = the<org.gradle.accessors.dm.LibrariesForLibs>()

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll("-Xjsr305=strict", "-Xannotation-default-target=param-property")
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

dependencies {
    // Import the Spring Boot BOM — manages versions for all Spring/Hibernate/Jackson deps.
    implementation(platform(libs.spring.boot.bom))

    // kotlin-reflect is required by Spring Data JPA for Kotlin entity/constructor discovery.
    implementation("org.jetbrains.kotlin:kotlin-reflect")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
